name: Auto-update Angular Dependencies

# Triggers the workflow to run at midnight every Sunday or manually
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update-angular:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      # Step 3: Cache Bun dependencies to speed up builds
      - name: Cache Bun modules
        uses: actions/cache@v3
        with:
          path: bun.lockb
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Step 4: Install dependencies using Bun
      - name: Install Dependencies
        run: bun install

      # Step 5: Update Angular Dependencies
      - name: Update Angular
        run: |
          bun add @angular/cli@latest
          npx ng update @angular/core @angular/cli --allow-dirty --force

      # Step 6: Create a new branch for the update
      - name: Create New Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b update-angular-dependencies

      # Step 7: Commit changes
      - name: Commit Changes
        run: |
          git add .
          git commit -m "chore: update Angular dependencies to latest"

      # Step 8: Push the branch
      - name: Push Changes
        run: |
          git push origin update-angular-dependencies

      # Step 9: Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-angular-dependencies
          title: "chore: Update Angular Dependencies"
          body: "This PR updates Angular dependencies to the latest versions."
          labels: "dependencies, angular, auto-update"
